version: '3'

services:
  composer:
    image: composer
    volumes:
      - .:/var/www/app/
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  php:
    image: php:7.3.7-cli-stretch
    working_dir: /var/www/app/
    volumes:
      - .:/var/www/app/
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
